module.exports = {
  posts: [
    { id: 1, title: "Lorem Ipsum", views: 254, user_id: 123 },
    { id: 2, title: "Sic Dolor amet", views: 65, user_id: 456 },
  ],
  users: [
    { id: 1, name: "Prinz" },
    { id: 2, name: "Fredrika" },
    { id: 3, name: "Jamison" },
    { id: 4, name: "Bobbee" },
    { id: 5, name: "Rodney" },
    { id: 6, name: "Broddy" },
    { id: 7, name: "Cicely" },
    { id: 8, name: "Salmon" },
    { id: 9, name: "Shea" },
    { id: 10, name: "Roseanne" },
    { id: 11, name: "Tamarah" },
    { id: 12, name: "Wilhelmina" },
    { id: 13, name: "Brennen" },
    { id: 14, name: "Lotty" },
    { id: 15, name: "Cybil" },
    { id: 16, name: "Skell" },
    { id: 17, name: "Andy" },
    { id: 18, name: "Coraline" },
    { id: 19, name: "Tomkin" },
    { id: 20, name: "Verge" },
  ],
  comments: [
    {
      id: 987,
      post_id: 1,
      body: "Consectetur adipiscing elit",
      date: new Date("2017-07-03"),
    },
    {
      id: 995,
      post_id: 1,
      body: "Nam molestie pellentesque dui",
      date: new Date("2017-08-17"),
    },
  ],
};
